name: Playwright CucumberJS Tests
on:
  workflow_dispatch: {}
  # schedule:
  #   - cron: '30 20 * * 1'
jobs:
  playwright:
    name: 'Playwright Tests'
    # runs-on: self-hosted
    runs-on: ubuntu-latest
    # container:
    #   image: mcr.microsoft.com/playwright:v1.38.1-jammy
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies using yarn
        run: yarn install

      - name: Install Playwright
        run: npx playwright install --with-deps

      - name: Run your tests using yarn
        run: yarn test

      - name: Run custom report using yarn
        run: yarn posttest
        if: always()

      - name: Upload report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test-result
          path: test-result/
          retention-days: 2
