name: Playwright CucumberJS Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  playwright:
    name: 'Playwright Tests'
    # runs-on: self-hosted
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.38.1-jammy
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies using yarn
        run: yarn install

      - name: Install Playwright
        run: npx playwright install --with-deps

      - name: Run your tests using yarn
        run: yarn test:report

      - name: Upload report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: cucumber-report
          path: cucumber-report/
          retention-days: 30
