name: E2E Tests

run-name: "E2E SwagLab ${{github.event.inputs.run-tag != '' && github.event.inputs.run-tag || ''}} ${{github.event.inputs.browser != '' && github.event.inputs.browser || ''}} Test Execution"

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      run-tag:
        type: choice
        description: Pick execution type to run
        options:
          - smoke
          - regression
        required: true
      browser:
        type: choice
        description: Pick execution type to run
        options:
          - chrome
          - firefox
          - webkit
        required: true
  schedule:
    - cron: '0 * * * 1-5'

env:
  BRAND:

jobs:
  run-matrix:
    if: github.event.inputs.run-tag=='' || github.event.inputs.browser==''
    strategy:
      matrix:
        BROWSER: ['chrome', 'firefox', 'webkit']
      fail-fast: false
    runs-on:
      - ubuntu-latest
    defaults:
      run:
        working-directory: .
    steps:
      - uses: actions/checkout@v3
      - name: Build Docker Image
        run: |-
          docker build -f Dockerfile -t playwright-docker .
      - name: Run E2E Cucumber tests in docker
        env:
          TEST_COMMAND: ${{ 'test' }}
        run: docker run -e BROWSER='${{matrix.BROWSER}}' -e VIDEO=true -v "$(pwd)":/app playwright-docker:latest sh -c "yarn install --frozen-lockfile && yarn ${{env.TEST_COMMAND}}"
      - name: Upload artifact
        if: always()
        uses: actions/upload-artifact@v3
        env:
          ARTIFACT_NAME: 'Report-${{matrix.BROWSER}}'
        with:
          name: '${{env.ARTIFACT_NAME}}'
          path: ./test-result
          if-no-files-found: warn
          retention-days: 7

  run-manual-trigger:
    if: github.event.inputs.run-tag!='' || github.event.inputs.browser!=''
    runs-on:
      - ubuntu-latest
    defaults:
      run:
        working-directory: .
    steps:
      - uses: actions/checkout@v3
      - name: Build Docker Image
        run: |-
          docker build -f Dockerfile -t playwright-docker .
      - name: Run E2E Cucumber tests in docker
        env:
          TEST_COMMAND: ${{ format('test:{0}',github.event.inputs.run-tag) }}
        run: docker run -e BROWSER='${{github.event.inputs.browser}}' -e VIDEO=true -v "$(pwd)":/app playwright-docker:latest sh -c "yarn install --frozen-lockfile && yarn ${{env.TEST_COMMAND}}"
      - name: Upload artifact
        if: always()
        uses: actions/upload-artifact@v3
        env:
          ARTIFACT_NAME: 'Report-${{github.event.inputs.run-tag}}-${{github.event.inputs.browser}}'
        with:
          name: '${{env.ARTIFACT_NAME}}'
          path: ./test-result
          if-no-files-found: warn
          retention-days: 7
