name: E2E Tests
run-name: 'E2E Swag Labs tests'

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      run-tag:
        type: choice
        description: Pick execution type to run
        options:
          - smoke
          - regression
        required: true
  schedule:
    - cron: '0 * * * 1-5'

env:
  BRAND:

jobs:
  run-matrix:
    strategy:
      matrix:
        BROWSER: [chrome]
      fail-fast: false
    runs-on:
      - ubuntu-latest
    defaults:
      run:
        working-directory: .
    steps:
      - uses: actions/checkout@v3
      - name: Build Docker Image
        run: |-
          docker build -f Dockerfile -t playwright-docker .
      - name: Run E2E Cucumber tests in docker with manual trigger
        if: ${{ github.event.inputs.run-tag }} != null
        env:
          TEST_COMMAND: ${{ github.event.inputs.run-tag != null && github.event.inputs.run-tag || 'test' }}
        run: docker run -v "$(pwd)":/app playwright-docker:latest  sh -c "yarn install --frozen-lockfile && yarn ${{env.TEST_COMMAND}}"

      # - name: Run E2E Cucumber tests in docker with schedule
      # if: ${{ github.event.inputs.run-tag }} == ''
      #   env:
      #     RUN_COMMAND: 'yarn install --frozen-lockfile && yarn test'
      #   run: docker run -v "$(pwd)":/app playwright-docker:latest  sh -c "${{env.RUN_COMMAND}}"

      # - name: List files in the repository
      #   run: |
      #     ls ${{ github.workspace }}
      - name: Upload artifact
        if: always()
        uses: actions/upload-artifact@v3
        env:
          ARTIFACT_NAME: 'Report-${{matrix.BROWSER}}'
        with:
          name: '${{env.ARTIFACT_NAME}}'
          path: ./test-result
          if-no-files-found: warn
          retention-days: 7
