name: E2E Tests
run-name: 'E2E Swag Labs tests'
on:
  workflow_dispatch: {}
  schedule:
    - cron: '30 20 * * 1-5'
env:
  BRAND: 'swaglabs'

jobs:
  run-matrix:
    strategy:
      matrix:
        BROWSER: [chrome]
      fail-fast: false
    runs-on:
      - ubuntu-latest
    defaults:
      run:
        working-directory: .
    steps:
      - uses: actions/checkout@v3
      - name: Build Docker Image
        run: |-
          docker build -f Dockerfile -t playwright-docker .
      - name: Run E2E Cucumber tests in docker
        env:
          RUN_COMMAND: 'yarn install --frozen-lockfile && yarn test'
        run: docker run playwright-docker:latest sh -c "${{env.RUN_COMMAND}}"
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Upload artifact
        if: always()
        uses: actions/upload-artifact@v3
        env:
          ARTIFACT_NAME: 'Report-${{matrix.BROWSER}}'
        with:
          name: '${{env.ARTIFACT_NAME}}'
          path: ${{ github.workspace }}/test-result
          if-no-files-found: warn
          retention-days: 7
